### ISSUE TITLE
Cannot find peers

### ISSUE THREAD

**Issue by jsalatas** [faircoin/faircoin-android-wallet#6]
It seems that currently it cannot find any peers. 

Could you please someone investigate and advice?

Thanks!

**Comment by jsalatas** [comment]
Just a follow-up: apparently the two dns seeds cannot be resolved 

faircoin2-seed2.fair-coin.org
faircoin2-seed1.fair-coin.org

https://github.com/faircoin/faircoinj/blob/4d6f3944835df6233d874e012f2d176a69f5a764/core/src/main/java/org/bitcoinj/params/MainNetParams.java#L73

so probably @thokon00 needs to have a look at this.

**Comment by thokon00** [comment]
The DNS-seed server died in a fire in the OVH data center in Strasbourg. DNS-seed entries have been reconfigured to return active peers.
